region_name = "eu-central-1"
organization_name = "msg systems"
department_name = "Automotive Technology"
project_name = "AT41"
stage = "dev"
network_name = "netgatewaytest"
network_cidr  = "10.0.0.0/16"
